language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
    secure: Dsvl6wpWser0W1pSTmbIAQrbeAamSOF5/13NuI5mCukLqGetHz5e+vSekjd7/HFUAZLBIG+T6NTgimj9YWEnjlGrReyHFyC4iiSzREaUPNGh3UJOAc3dgv9cPUVbijzacpbagMyIeNNMOW0/+FRvjK9lYOElGrnOP3bWIRs2mgLYVdSSkv2zv7EMjxQFE6oAR4KwYb2bweeAJ6DV8/42Ge5Eccpmlw/PDABieIBlBV6u+m8hEHdmduDS+FjG3EG5hjEYJwmDqITm1zR6TSLxgzErVY2ESuU9gc1vsVZdsyqrB+dZPId8svqmpf3KTJy8lsk1PGOGvINywklZXwrnyiMye6bo0uziHpOmB0qvpx29Apttj3Udw0tpdE2jHrGWyFpDaEK+JQWaCEvry4xqmV2/6bsSjH4HppU6Yzk10peN3dUm9hE9bm/9KK6x7+8LfCJ7TR+hKDgHJkVvJ+PoY+lvk594QGVZloE5cJCqQuhhkX8CHIgEuACgxqvhtlXmxfEk+39irVsjLD8KbSckpXf+4UIChvT8c36wpTyZtD3QTWlEPuG5DKzbe45HB2T2tNRzRaC2b/3LmhPOulCS+Nmi1CfcneYnkSwuVxiPrIyR90vrqiBDqAsUAB7dxaIeQsDDS4OFve7BhwI1/0wiQapThg+uMBTBCg1dfqoiEQU=
